# 源码： RemoteAddrRoutePredicateFactory
spring:
  cloud:
    gateway:
      routes:
        - id: remoteaddr_route
          uri: lb://test
          predicates:
            - RemoteAddr=192.168.3.1/24
# 请求IP 在 192.168.3.1 - 192.168.3.24 之间能被正常转发